language: node_js
node_js: node
cache:
  directories:
  - node_modules
  env:
- CI=true
deploy:
  provider: heroku
  api_key: 8ba46910-616f-4516-a7f3-066567d184fa
  app: sleepy-cliffs-39941
  on:
    repo: jmutt78/the-startup
